### ISSUE TITLE
Signal app overlays contact list with only signal contacts

### ISSUE THREAD

**Issue by Machion** [SimpleMobileTools/Simple-Contacts#257]
Another strange thing I just realized: 
I installed signal and now in your app I can only see contacts, which are also in signal. Non-signal accounts are gone. I don't know, if there were deleted or just hidden. Is this a signal problem/wrong setting?

_Originally posted by @Machion in https://github.com/SimpleMobileTools/Simple-Contacts/issues/255#issuecomment-423099379_ 

The filter option just gives me the checkboxes "signal" and "phone storage (not visible by other apps)" 
Disabling "Try filtering dublicate contacts" doesn't work either. 
Uninstalling signal restores complete contact list.

**Comment by tibbi** [comment]
retry with 6.1.2 released soon please

**Comment by Machion** [comment]
Sorry for my late answer. 
I tested version 6.1.2 and now i can't see any contacts at all. No matter if the filter checkboxes (signal, phone storage) are checked or not. Tested on android 9 and with a reinstall of the app.

**Comment by tibbi** [comment]
try it with 6.2.0 :)

**Comment by Machion** [comment]
With version 6.2.0 I can't see any contacts at all now.
7. Januar 2019 22:50, "Tibor Kaputa" <notifications@github.com (mailto:notifications@github.com?to=%22Tibor%20Kaputa%22%20<notifications@github.com>)> schrieb:
	try it with 6.2.0 :)

**Comment by tibbi** [comment]
update to 6.3.0, some issues have been fixed

**Comment by Machion** [comment]
With version 6.3.0 the issue still remains.
29. Januar 2019 21:56, "Tibor Kaputa" <notifications@github.com (mailto:notifications@github.com?to=%22Tibor%20Kaputa%22%20<notifications@github.com>)> schrieb: 
	update to 6.3.0, some issues have been fixed
