### ISSUE TITLE
Alphabetic quick scroller selects wrong position in contacts list

### ISSUE THREAD

**Issue by Gitoffthelawn** [SimpleMobileTools/Simple-Contacts#646]
Simple Contacts v6.13.2: the alphabetic quick scroller does not go to the correct position in the contacts list, nor does the correct letter get magnified.  For example, if I long-press the letter S, it will show V and go to contacts with names beginning with V.

**Comment by tibbi** [comment]
isnt the scrollbar higher than the screen? It glitches in that case, it is already reported somewhere.

**Comment by Gitoffthelawn** [comment]
In the alphabetic quick scroller, the letter V is cut off vertically half-way, making it look like a mini backslash followed by a forward slash: \ /. Below that is an empty area approximately the height of a single letter. Below that, the screen ends.

I don't think the alphabetic quick scroller is correctly coded to work on screens of different sizes/resolutions.

**Comment by tibbi** [comment]
should be fixed already

**Comment by Gitoffthelawn** [comment]
@tibbi I just took a look at it again.  I installed 6.14.3.  It's better than before, but unfortunately, still broken:

1. The last item in the quick scroller is cut off by a few pixels.
2. Moving the scroller up or down quickly results in the crashing about half the time.
3. Special characters are all listed at the bottom of the scroller, instead of the top, like Android.  For example, the plus sign and double-chevrons.

BTW, IIRC, the Dialer app was still broken with regards to the quick scroller as well.
