### ISSUE TITLE
No display of the names and other fields

### ISSUE THREAD

**Issue by RUMO-Barsoom** [SimpleMobileTools/Simple-Contacts#743]
Hello,
I have some contacts whose names are shown to me in the overview. However, when I call the contact, first name and last name are missing, as well as the contents of other fields.
When I click on edit, the fields are empty.
The data is synchronized from my Nextcloud with DAVx5. 
Several other contact apps do not have this problem and display all the information.

For example, I have the matrix ID stored for 2 contacts. In the SimpleContacts app, the field appears for one contact, but not the other.

I haven't figured out what the difference is between the contacts that it shows up on some and not others.

**Comment by tibbi** [comment]
what contact source are you saving the contact to? I mean the last field at the contact details screen. Does it say your email, Phone, SIM or something like that?

**Comment by RUMO-Barsoom** [comment]
Hello Tibbi,
I sadly don't understand.
I wrote, that I synchronize my Contacts with DAVx5.
That way all my Contacts have as last field "Kontakte >Name of Cloud>".
Both exampled Contacts are from Nextcloud. 
In one example contact I have names and IM-Messenger filled, by the other contact not.

And I saw a few minutes ago that I can't add new fields. Only the default existing ones.

Regards, Rumo

**Comment by tibbi** [comment]
If you click on a contact in Simple Contacts, by default the View details screen should open. The last icon at the left side is a silhouete, what is at the right side of it? If there are more entries, you have the given contact stored multiple times and each entry might have some other fields filled in.
![Screenshot_20211129-182416](https://user-images.githubusercontent.com/528931/143914413-a8aaf70d-b753-4fd4-b9c2-0e4a7c7415a3.jpg)

**Comment by RUMO-Barsoom** [comment]
Hello Tibbi,
I sadly don't understand.
I wrote, that I synchronize my Contacts with DAVx5.
That way all my Contacts have as last field "Kontakte >Name of Cloud>".
Both exampled Contacts are from Nextcloud. 
In one example I have names and IM-Messenger filled, by the other contact not.

And I saw a few minutes ago that I can't add new fields. Only the default existing ones.

Regards, Rumo

**Comment by RUMO-Barsoom** [comment]
I have over 700 Contacts. They all are only in Nextcloud and synchronized to my Phone.
I can click on Symbol you answered and can switch between Nextcloud Contacts, 2Gmail Accounts and the device storage.
By all I see the same details. There is no synchronization to Gmail or Sim. And selected is the Nextcloud.

**Comment by RUMO-Barsoom** [comment]
I get the update on fdroid today. (Version 6.16.3)
But still not all fields are displayed and some fields are displayed for one contact but not for the other.
(as an example InstantMessenger fields, first name, last name).
All data still comes from Nextcloud and is synced with DavX5 and displayed on other contact apps.

**Comment by dailygravy** [comment]
This bug may be related to one that I have discovered. If you create a contact that includes the organisation field using another app like Google Contacts, the contact's name is correctly displayed in Simple Contact's contact list. However, if you edit such a contact with Simple Contacts, the name-related fields are all empty.

This bug can also be reproduced when contacts are synced using DecSync CC, but I suspect it can also happen with DavX5:

- Create a contact that includes organisation info with Simple Contacts.
- Observe that when re-editing this contact all name-related fields will still be present.
- In DecSync CC, make sure contacts are fully synced, then temporarily disable the addressbook before re-enabling it.
- In Simple Contacts, observe that the contact is seemingly restored correctly in the contact list, as it displays the name correctly. However, as soon as you edit it, all the name-related fields disappear.

**Comment by hjudt** [comment]
I am not sure if this is related, but on my Samsung Note 8 (Android 9), I have contacts where no mail addresses are shown, though the Samsung Contacts app does not have this problem and shows all fields.
But on my Samsung Note 3, which I have updated to LineageOS (Android 11), the e-mail addresses are shown in Simple Contacts for the same contact, and I can also edit them.
The contacts are synced by DAVx5 and stored on a radicale address book/caldav server.

It seems, though that in my case only e-mail addresses are affected, no other fields. I have created and edited all contacts using the thunderbird cardbook extension.

**Comment by rlieger** [comment]
I noticed a similar behaviour, where the name fields are not displayed when editing a contact that contains an organisation and that was synced using DAVx5 from NextCloud.

I managed to track down this behaviour to ContactHelper.kt::parseContactCursor(). If a contact contains Organizational data, then the context contains two lines of data, one of MIME-type vnd.android.cursor.item/organization and one of type .../name. However parseContactCursor() just goes uses cursor.moveToFirst() and parses the contents of the first line of data. It never calls cursor.moveToNext() to check if there are additional lines of data. Thus if the first line contains the .../origanization data, the name fields are (deliberatly, correctly) skipped (because the contain data not suitable for display) but the .../name data is never read and thus the name fields remain empty...

In my experiments it seems that all the other payload fields (e.g. address, phone number, emails) are present in both the organization and name data sets, so we can copy them from either set.

**Comment by tibbi** [comment]
should be fixed already

**Comment by hjudt** [comment]
While now more fields are shown correctly (like all phone number and addresses), e-mail addresses are still missing (entirely it seems). The Samsung contacts app on my Note 8 shows them all.

**Comment by tibbi** [comment]
you can enable extra fields from the top menu, but that is unrelated to this issue

**Comment by hjudt** [comment]
I know, and these fields are activated. I see the mail addresses for some contacts, but not for all of them.

**Comment by RUMO-Barsoom** [comment]
Yeah, I miss so much fields I have in my Nextcloud-Contacts.
